# NB: don't set `language: haskell` here
# See https://github.com/hvr/multi-ghc-travis for more information

env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.2

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.20 update
 - cabal-1.20 sandbox init
 - cabal-1.20 install --only-dependencies --enable-tests -j

script:
 - cabal-1.20 configure --enable-tests -v2
 - cabal-1.20 build
 - cabal-1.20 test
 - cabal-1.20 check
 - cabal-1.20 sdist
# check that the generated source-distribution can be built & installed
 - export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   cabal-1.20 sandbox init
   if [ -f "$SRC_TGZ" ]; then
      cabal-1.20 install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

notifications:
  email:
    - kolmodin@gmail.com
